### ISSUE TITLE
running help on apbs-mem-potential.py  fails

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/BornProfiler#5]
I created setup dirs with
```
apbs-bornprofile-init.py
```
and then want to just see the help:
```
(bp) oliver@spudda:~/Projects/Methods$ apbs-mem-potential.py -h
Traceback (most recent call last):
  File "/nfs/homes2/oliver/.virtualenvs/bp/bin/apbs-mem-potential.py", line 50, in <module>
    import bornprofiler.electrostatics
  File "/nfs/homes2/oliver/.virtualenvs/bp/local/lib/python2.7/site-packages/bornprofiler/electrostatics.py", line 55, in <module>
    'solvation_no_membrane': read_template('solvation_no_membrane.in'),
  File "/nfs/homes2/oliver/.virtualenvs/bp/local/lib/python2.7/site-packages/bornprofiler/bpio.py", line 382, in read_template
    fn = config.get_template(filename)
  File "/nfs/homes2/oliver/.virtualenvs/bp/local/lib/python2.7/site-packages/bornprofiler/config.py", line 252, in get_template
    templates = [_get_template(s) for s in utilities.asiterable(t)]
  File "/nfs/homes2/oliver/.virtualenvs/bp/local/lib/python2.7/site-packages/bornprofiler/config.py", line 308, in _get_template
    raise ValueError(errmsg)
ValueError: Failed to locate the template file 'solvation_no_membrane.in'.

```

This should work.

**Comment by orbeckst** [comment]
fixed in e1ee25613919c1a937513ac48416598bb9a0f86d
